### ISSUE TITLE
await & async support 

### ISSUE THREAD

**Issue by b3rew** [moe-szyslak/Lethal-Weapon-5#1]
I far as i know await & async are not supported on ES6 (I might be wrong) so what do you recommend using NodeJs version 6.x.x

or I could just use 'nightly' versions but

> Disclaimer: the async/await functionality is only available in the nightly, unstable version of Node.js

Edit: include the quote

**Comment by moe-szyslak** [comment]
Async/Await are just syntactic sugars over generators. The feature has been available without the flag [`--harmony`] since Node 7.6 [released 2017-02-21, in JavaScript time that's like 2 years ago]

**Comment by moe-szyslak** [comment]
- [ ] Add minimum node version required to README.md
